# Generated by Django 5.2.6 on 2025-09-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default='f792fc7b-7b60-4387-b5e1-8b2b123f3d32', on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chats.conversation'),
            preserve_default=False,
        ),
    ]
