<<<<<<< HEAD
version: '3.8'

services:
  # Django app service
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
=======
version: "3.9"

services:
    web:
          build: .
                command: python manage.py runserver 0.0.0.0:8000
                      ports:
                              - "8000:8000"
                                    env_file:
                                            - .env
                                                  depends_on:
                                                          - db
                                                                  - redis

                                                                      db:
                                                                            image: postgres:14
                                                                                  environment:
                                                                                          POSTGRES_DB: airbnb_db
                                                                                                  POSTGRES_USER: airbnb_user
                                                                                                          POSTGRES_PASSWORD: airbnb_pass
                                                                                                                volumes:
                                                                                                                        - postgres_data:/var/lib/postgresql/data

                                                                                                                            redis:
                                                                                                                                  image: redis:6
                                                                                                                                        ports:
                                                                                                                                                - "6379:6379"

                                                                                                                                        volumes:
                                                                                                                                            postgres_data:

>>>>>>> 43038a253a1d92ed908aff8639e165d36670c4e6
