version: "3.9"

services:
    web:
          build: .
                command: python manage.py runserver 0.0.0.0:8000
                      ports:
                              - "8000:8000"
                                    env_file:
                                            - .env
                                                  depends_on:
                                                          - db
                                                                  - redis

                                                                      db:
                                                                            image: postgres:14
                                                                                  environment:
                                                                                          POSTGRES_DB: airbnb_db
                                                                                                  POSTGRES_USER: airbnb_user
                                                                                                          POSTGRES_PASSWORD: airbnb_pass
                                                                                                                volumes:
                                                                                                                        - postgres_data:/var/lib/postgresql/data

                                                                                                                            redis:
                                                                                                                                  image: redis:6
                                                                                                                                        ports:
                                                                                                                                                - "6379:6379"

                                                                                                                                        volumes:
                                                                                                                                            postgres_data:

