pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-u root'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/qwabena37/alx-backend-python.git', branch: 'main'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install --upgrade pip'
                sh 'pip install pytest'
                sh 'pip install -r messaging_app/requirements.txt || true'
            }
        }

        stage('Test') {
            steps {
                sh 'pytest messaging_app/tests --maxfail=1 --disable-warnings -q'
            }
        }
    }
}
